criaCartao(
    'ANimais de eStImação',
    'Qual é o animal mais comum do mundo?',
    'É o cachorro',
    ' Qual é a espectativa média de um gato doméstico?',
    'De 16 a 20 anos.',
    'Por que os cachorros abanam o rabo?',
    'Para expressar emoções, como por exemplo a felicidade.',
    'Qual o animal doméstico que vive por mais tempo?',
    'Cacatua',
    'Qual é a estimativa de vida média de um hamster?',
    'De 3 a 4 anos',
    'Quantas raças existem de porquinho-da-índia?',
    'Existem mais de 20 raças diferentes de porquinhos da índia',
)